require './only-letters.client.directive'
require './email-validator.client.directive'
require './only-letters-and-digits.client.directive'
require './confirm-password.client.directive'
require './user-name-exists.client.directive'
require './date-formatter.client.directive'
